# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

use_frameworks!

def shared_pods
    pod 'Alamofire'
    pod 'ObjectMapper'
    pod 'BetterCodable', '~> 0.1.0'
#    pod 'NVActivityIndicatorView'
    pod 'Kingfisher', '~> 7.0'
    pod 'IBAnimatable'
    pod 'IQKeyboardManagerSwift', '6.5.15'
    pod 'NVActivityIndicatorView/Extended'
end

target 'MovieSearch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  # Pods for iPadPOS
  shared_pods
  
#  target 'MovieSearchTests' do
#    inherit! :search_paths
#  end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
  installer.aggregate_targets.each do |target|
    target.xcconfigs.each do |variant, xcconfig|
      xcconfig_path = target.client_root + target.xcconfig_relative_path(variant)
      IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
    end
  end
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.base_configuration_reference.is_a? Xcodeproj::Project::Object::PBXFileReference
        xcconfig_path = config.base_configuration_reference.real_path
        IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
      end
    end
    end
  end
end
  
